### ISSUE TITLE
Are multiple API servers supported?

### ISSUE THREAD

**Issue by NikkotheAIDEV** [skx/sos#36]
Are multiple API servers supported? If yes, how?

**Comment by skx** [comment]
You can run multiple API servers, providing they all talk to the same blob-servers, it will work as expected.

e.g.

> load-balancer   ->  [ api1        api2 ]

As for how to do it:  Just launch more than one, if you wish, passing the same list of configured blob-servers.

**Comment by NikkotheAIDEV** [comment]
So a load balancer infront of multiple API servers and pass the same blob servers to each of the API servers, right?

**Comment by skx** [comment]
Yes.
